title: Team CTRL
url: https://team-ctrl.github.io
repository: team-ctrl/team-ctrl.github.io

permalink: pretty
production: true

plugins:
 - jekyll-feed
 - jekyll-redirect-from
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-avatar
 - jemoji
 - jekyll-mentions
 - jekyll-include-cache

#Build Settings
markdown: kramdown

kramdown:
  input: GFM
  auto_ids: false

excludes:
  - Gemfile
  - Gemfile.lock
  - ".sh"
  - README.md
  - ".gitignore"

  
defaults:
- scope:
    path: ""
  values:
    layout: default
- scope:
    path: ""
    type: pages
  values:
    layout: page
- scope:
    path: ""
    type: posts
  values:
    layout: post
    list: true
